version: '3'
services:
  app-client-redis:
    build: ../../applications/client
    environment:
      MODE: dev
      REDISHOST: '$DOCKERHOST'
      REDISPORT: '6379'
    extra_hosts:
    - "redis-server: $DOCKERHOST"
  app-server-redis:
    build: ../../applications/server
    environment:
      MODE: dev
      REDISHOST: '$DOCKERHOST'
      REDISPORT: '6379'
    extra_hosts:
    - "redis-server: $DOCKERHOST"