version: '3'
services:
  app-client-generic-avro:
    image: es/kafka-test-app-client:1.0.0
    container_name: app-client-generic-avro
    environment:
      PROCESS: genericAvro
    volumes:
      - logs:/var/log/processes
    #entrypoint: /opt/app/run_jar.sh #/bin/sh
    #entrypoint: ./run_jar.sh #/bin/sh
    entrypoint: /bin/sh
    #entrypoint: ls
    #entrypoint:
    #   - /bin/sh /opt/app/run_jar.sh
    #   - /bin/sh
    #entrypoint: /bin/sh /opt/app/run_jar.sh
    tty: true     #network_mode: host
  app-server-generic-avro:
    image: es/kafka-test-app-server:1.0.0
    container_name: app-server-generic-avro
    environment:
      PROCESS: genericAvro
    volumes:
    - logs:/var/log/processes
    entrypoint: /bin/sh /opt/app/run_jar.sh
    #entrypoint: /bin/sh
    tty: true
volumes:
  logs: {}