version: '3'
services:
  app-client-postgre-sql:
    build: ../../applications/client
    environment:
      MODE: dev
      POSTGRE_SERVER: '$DOCKERHOST:5432'
    extra_hosts:
    - "postgre-sql: $DOCKERHOST"
